package com.example.smartremainder

import android.app.DatePickerDialog
import android.app.TimePickerDialog
import android.os.Bundle
import android.view.View
import android.widget.Button
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.example.smartremainder.databinding.ActivityAddMedicineBinding
import java.util.Calendar

class AddMedicineActivity : AppCompatActivity() {

    private lateinit var binding: ActivityAddMedicineBinding
    private lateinit var dbHelper: DatabaseHelper
    private lateinit var alarmScheduler: AlarmScheduler

    private var selectedFrequency: String? = null
    private var selectedDuration: String? = null

    private lateinit var frequencyButtons: List<Button>
    private lateinit var durationButtons: List<Button>

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityAddMedicineBinding.inflate(layoutInflater)
        setContentView(binding.root)

        dbHelper = DatabaseHelper(this)
        alarmScheduler = AlarmScheduler(this)

        initializeButtonGroups()
        setupClickListeners()
    }

    private fun initializeButtonGroups() {
        frequencyButtons = listOf(
            binding.btnOnceDaily, binding.btnTwiceDaily, binding.btnThriceDaily,
            binding.btnEveryHour, binding.btnEvery6Hours, binding.btnEvery12Hours
        )
        durationButtons = listOf(
            binding.btn7days, binding.btn14days, binding.btn30days,
            binding.btn90days, binding.btnOngoing
        )
    }

    private fun setupClickListeners() {
        binding.btnBack.setOnClickListener { finish() }
        binding.btnCancel.setOnClickListener { finish() }

        binding.tvDate.setOnClickListener { showDatePickerDialog() }
        binding.tvTime.setOnClickListener { showTimePickerDialog() }

        frequencyButtons.forEach { button ->
            button.setOnClickListener { 
                handleSelection(button, frequencyButtons)
                selectedFrequency = button.text.toString()
            }
        }

        durationButtons.forEach { button ->
            button.setOnClickListener { 
                handleSelection(button, durationButtons)
                selectedDuration = button.text.toString()
            }
        }

        binding.btnAddMedication.setOnClickListener {
            saveMedication()
        }
    }

    private fun handleSelection(selectedButton: Button, group: List<Button>) {
        group.forEach { button ->
            button.isSelected = (button.id == selectedButton.id)
        }
    }

    private fun showDatePickerDialog() {
        val calendar = Calendar.getInstance()
        val datePickerDialog = DatePickerDialog(
            this,
            { _, year, month, dayOfMonth ->
                val date = "$year-${month + 1}-$dayOfMonth"
                binding.tvDate.text = date
            },
            calendar.get(Calendar.YEAR),
            calendar.get(Calendar.MONTH),
            calendar.get(Calendar.DAY_OF_MONTH)
        )
        datePickerDialog.show()
    }

    private fun showTimePickerDialog() {
        val calendar = Calendar.getInstance()
        val timePickerDialog = TimePickerDialog(
            this,
            { _, hourOfDay, minute ->
                val time = String.format("%02d:%02d", hourOfDay, minute)
                binding.tvTime.text = time
            },
            calendar.get(Calendar.HOUR_OF_DAY),
            calendar.get(Calendar.MINUTE),
            true
        )
        timePickerDialog.show()
    }

    private fun saveMedication() {
        val medicineName = binding.etMedicineName.text.toString().trim()
        val dosage = binding.etDosage.text.toString().trim()
        val startDate = binding.tvDate.text.toString()
        val time = binding.tvTime.text.toString()
        val notes = binding.etNotes.text.toString().trim()
        val reminderEnabled = binding.switchReminder.isChecked
        val refillEnabled = binding.switchRefill.isChecked
        val currentSupply = binding.etCurrentSupply.text.toString().toIntOrNull() ?: 0
        val maxSupply = binding.etMaxSupply.text.toString().toIntOrNull() ?: 0

        if (medicineName.isBlank() || selectedFrequency == null || selectedDuration == null || startDate == "Select Start Date" || time == "Select Medication Time") {
            Toast.makeText(this, "Please fill all required fields.", Toast.LENGTH_SHORT).show()
            return
        }

        val newMedication = Medication(
            id = 0, // ID is auto-generated by the database
            name = medicineName,
            dosage = dosage,
            frequency = selectedFrequency!!,
            duration = selectedDuration!!,
            startDate = startDate,
            time = time,
            reminderEnabled = reminderEnabled,
            refillEnabled = refillEnabled,
            notes = notes,
            currentSupply = currentSupply,
            maxSupply = maxSupply
        )

        val id = dbHelper.addMedication(newMedication)

        if (id != -1L) {
            if (reminderEnabled) {
                alarmScheduler.schedule(newMedication.copy(id = id))
            }
            Toast.makeText(this, "Medication added successfully!", Toast.LENGTH_SHORT).show()
            finish()
        } else {
            Toast.makeText(this, "Failed to add medication.", Toast.LENGTH_SHORT).show()
        }
    }
}
